=== sarnobat/imperial_college_2001-2004/Year 3/MIPS Project/cvs/yams/src/Instruction_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Qian Qiao (private) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Instructions">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Instruction" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="OperandTypes" type="xs:string" maxOccurs="unbounded"/>
							<xs:element name="Javacode" type="xs:string" minOccurs="0"/>
							<xs:element name="Type">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="fixedRt" type="xs:boolean"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="CoreMachineCode" type="xs:string" minOccurs="0"/>
							<xs:element name="MachineCodeRepresentations">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Representation" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="OperandsCoding" type="xs:string"/>
													<xs:element name="MachineCode" type="xs:string"/>
													<xs:element name="Operands" minOccurs="0">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Op" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="Number" type="xs:int"/>
																			<xs:element name="Type" type="xs:string"/>
																			<xs:element name="Mask" type="xs:double"/>
																			<xs:element name="EncodeBits" type="xs:int"/>
																			<xs:element name="OutputBits" type="xs:int"/>
																			<xs:element name="OffSetMode" type="xs:int"/>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Help" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="FullName" type="xs:string"/>
										<xs:element name="Format" type="xs:string"/>
										<xs:element name="Description" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== sarnobat/imperial_college_2001-2004/Year 3/MIPS Project/cvs/yams/src/Instruction_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<Instructions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\eclipse\workspace\yams\src\Instruction_file.xsd">
	<!--
	<Instruction>
		<Name></Name>
		<OperandTypes></OperandTypes>
		<Javacode></Javacode>
		<Type>Regular</Type>
		<CoreMachineCode></CoreMachineCode>
		<MachineCodeRepresentations>
		</MachineCodeRepresentations>
		<Help>
			<FullName></FullName>
			<Format></Format>
			<Description></Description>
		</Help>
	</Instruction>
-->
	<!-- accepted operand types
Operand.TYPE_REGISTER
Operand.TYPE_ADDRESSING
Operand.TYPE_IMMEDIATE
Operand.TYPE_LABEL
-->
	<Instruction>
		<Name>add</Name>
		<OperandTypes>Operand.TYPE_REGISTER, Operand.TYPE_REGISTER, Operand.TYPE_REGISTER</OperandTypes>
		<OperandTypes>Operand.TYPE_REGISTER, Operand.TYPE_REGISTER, Operand.TYPE_IMMEDIATE</OperandTypes>
		<Javacode>
		regs.setReg(rd, regs.getReg(rs) + regs.getReg(rt));
		</Javacode>
		<Type>Extended</Type>
		<CoreMachineCode>000000bbbbbcccccaaaaa00000100000</CoreMachineCode>
		<MachineCodeRepresentations>
			<Representation>
				<OperandsCoding>111</OperandsCoding>
				<MachineCode>000000bbbbbcccccaaaaa00000100000</MachineCode>
			</Representation>
			<Representation>
				<OperandsCoding>110</OperandsCoding>
				<MachineCode>001000bbbbbaaaaacccccccccccccccc</MachineCode>
				<Operands>
					<Op>
						<Number>3</Number>
						<Type>0</Type>
						<Mask>1111111111111111</Mask>
						<EncodeBits>16</EncodeBits>
						<OutputBits>16</OutputBits>
						<OffSetMode>2</OffSetMode>
					</Op>
				</Operands>
			</Representation>
			<Representation>
				<OperandsCoding>11a</OperandsCoding>
				<MachineCode>00111100000aaaaadddddddddddddddd001101aaaaaaaaaacccccccccccccccc000000bbbbbaaaaaaaaaa00000100000</MachineCode>
				<!-- 	lui a d 
						addi a c 001000aaaaaaaaaacccccccccccccccc changed to ori
						add a a b
				-->
				<Operands>
					<Op>
						<Number>3</Number>
						<Type>a</Type>
						<Mask>11111111111111111111111111111111</Mask>
						<EncodeBits>32</EncodeBits>
						<OutputBits>32</OutputBits>
						<OffSetMode>2</OffSetMode>
					</Op>
				</Operands>
			</Representation>
		</MachineCodeRepresentations>
		<Help>
			<FullName/>
			<Format/>
			<Description/>
		</Help>
	</Instruction>
	<Instruction>
		<Name>addu</Name>
		<OperandTypes>Operand.TYPE_REGISTER, Operand.TYPE_REGISTER, Operand.TYPE_REGISTER</OperandTypes>
		<Javacode>
		regs.setReg(rd, regs.getReg(rs) + regs.getReg(rt));
		</Javacode>
		<Type>Regular</Type>
		<MachineCodeRepresentations>
			<Representation>
				<OperandsCoding>111</OperandsCoding>
				<MachineCode>000000bbbbbcccccaaaaa00000100001</MachineCode>
			</Representation>
		</MachineCodeRepresentations>
		<Help>
			<FullName/>
			<Format/>
			<Description/>
		</Help>
	</Instruction>
	<Instruction>
		<Name>slt</Name>
		<OperandTypes>Operand.TYPE_REGISTER, Operand.TYPE_REGISTER, Operand.TYPE_REGISTER</OperandTypes>
		<Javacode>
		if(regs.getReg(rs) &lt; regs.getReg(rt)) {
			regs.setReg(rd, 1);
		}
		else {
			regs.setReg(rd, 0);
		}
		</Javacode>
		<Type>Regular</Type>
		<MachineCodeRepresentations>
			<Representation>
				<OperandsCoding>111</OperandsCoding>
				<MachineCode>000000bbbbbcccccaaaaa00000101010</MachineCode>
			</Representation>
		</MachineCodeRepresentations>
		<Help>
			<FullName/>
			<Format/>
			<Description/>
		</Help>
	</Instruction>
	<Instruction>
		<Name>addi</Name>
		<OperandTypes>Operand.TYPE_REGISTER, Operand.TYPE_REGISTER, Operand.TYPE_IMMEDIATE</OperandTypes>
		<Javacode>
		regs.setReg(rt, regs.getReg(rs) + i);
		</Javacode>
		<Type>Regular</Type>
		<MachineCodeRepresentations>
			<Representation>
				<OperandsCoding>110</OperandsCoding>
				<MachineCode>001000bbbbbaaaaacccccccccccccccc</MachineCode>
				<Operands>
					<Op>
						<Number>3</Number>
						<Type>0</Type>
						<Mask>1111111111111111</Mask>
						<EncodeBits>16</EncodeBits>
						<OutputBits>16</OutputBits>
						<OffSetMode>2</OffSetMode>
					</Op>
				</Operands>
			</Representation>
		</MachineCodeRepresentations>
		<Help>
			<FullName/>
			<Format/>
			<Description/>
		</Help>
	</Instruction>
	<Instruction>
		<Name>sub</Name>
		<OperandTypes>Operand.TYPE_REGISTER, Operand.TYPE_REGISTER, Operand.TYPE_REGISTER</OperandTypes>
		<OperandTypes>Operand.TYPE_REGISTER, Operand.TYPE_REGISTER, Operand.TYPE_IMMEDIATE</OperandTypes>
		<Javacode>
		regs.setReg(rd, regs.getReg(rs) - regs.getReg(rt));
		</Javacode>
		<Type>Extended</Type>
		<CoreMachineCode>000000bbbbbcccccaaaaa00000100010</CoreMachineCode>
		<MachineCodeRepresentations>
			<Representation>
				<OperandsCoding>111</OperandsCoding>
				<MachineCode>000000bbbbbcccccaaaaa00000100010</MachineCode>
			</Representation>
			<Representation>
				<OperandsCoding>110</OperandsCoding>
				<MachineCode>0010000000000001cccccccccccccccc000000bbbbb00001aaaaa00000100010</MachineCode>
				<Operands>
					<Op>
						<Number>3</Number>
						<Type>0</Type>
						<Mask>1111111111111111</Mask>
						<EncodeBits>16</EncodeBits>
						<OutputBits>16</OutputBits>
						<OffSetMode>2</OffSetMode>
					</Op>
				</Operands>
			</Representation>
			<Representation>
				<OperandsCoding>11a</OperandsCoding>
				<MachineCode>0011110000000001dddddddddddddddd0011010000100001cccccccccccccccc000000bbbbb00001aaaaa00000100010</MachineCode>
				<Operands>
					<Op>
						<Number>3</Number>
						<Type>a</Type>
						<Mask>11111111111111111111111111111111</Mask>
						<EncodeBits>32</EncodeBits>
						<OutputBits>32</OutputBits>
						<OffSetMode>2</OffSetMode>
					</Op>
				</Operands>
			</Representation>
		</MachineCodeRepresentations>
		<Help>
			<FullName/>
			<Format/>
			<Description/>
		</Help>
	</Instruction>
	<Instruction>
		<Name>mult</Name>
		<OperandTypes>Operand.TYPE_REGISTER, Operand.TYPE_REGISTER</OperandTypes>
		<Javacode>
		long left = regs.getReg(rs);
		long right = regs.getReg(rt);
		long product = left * right;
		int lo = (int) (product &amp; 0xffffffff);
		int hi = (int) (product &gt;&gt;&gt; 32);
		regs.setReg("LO", lo);
		regs.setReg("HI", hi);
		</Javacode>
		<Type>Regular</Type>
		<MachineCodeRepresentations>
			<Representation>
				<OperandsCoding>11</OperandsCoding>
				<MachineCode>000000aaaaabbbbb0000000000011000</MachineCode>
			</Representation>
		</MachineCodeRepresentations>
		<Help>
			<FullName/>
			<Format/>
			<Description/>
		</Help>
	</Instruction>
	<Instruction>
		<Name>mul</Name>
		<OperandTypes>Operand.TYPE_REGISTER, Operand.TYPE_REGISTER, Operand.TYPE_REGISTER</OperandTypes>
		<OperandTypes>Operand.TYPE_REGISTER, Operand.TYPE_REGISTER, Operand.TYPE_IMMEDIATE</OperandTypes>
		<Type>Pseudoinstruction</Type>
		<MachineCodeRepresentations>
			<Representation>
				<OperandsCoding>111</OperandsCoding>
				<MachineCode>000000bbbbbccccc00000000000110000000000000000000aaaaa00000010010</MachineCode>
				<!-- 	mul b c
						mtlo a
				-->
			</Representation>
			<Representation>
				<OperandsCoding>110</OperandsCoding>
				<MachineCode>0010000000000001cccccccccccccccc00000000001bbbbb00000000000110000000000000000000aaaaa00000010010</MachineCode>
				<!-- 	addi a c  00100000000aaaaacccccccccccccccc changed to ori changed back
						mult b c
						mflo a
				-->
				<Operands>
					<Op>
						<Number>3</Number>
						<Type>0</Type>
						<Mask>1111111111111111</Mask>
						<EncodeBits>16</EncodeBits>
						<OutputBits>16</OutputBits>
						<OffSetMode>2</OffSetMode>
					</Op>
				</Operands>
			</Representation>
			<Representation>
				<OperandsCoding>11a</OperandsCoding>
				<MachineCode>0011110000000001dddddddddddddddd0011010000100001cccccccccccccccc00000000001bbbbb00000000000110000000000000000000aaaaa00000010010</MachineCode>
				<!-- 	lui a d 
						addi a c 001000aaaaaaaaaacccccccccccccccc changed to ori
						mult b a
						mflo a
				-->
				<Operands>
					<Op>
						<Number>3</Number>
						<Type>a</Type>
						<Mask>11111111111111111111111111111111</Mask>
						<EncodeBits>32</EncodeBits>
						<OutputBits>32</OutputBits>
						<OffSetMode>2</OffSetMode>
					</Op>
				</Operands>
			</Representation>
		</MachineCodeRepresentations>
		<Help>
			<FullName/>
			<Format/>
			<Description/>
		</Help>
	</Instruction>
	<Instruction>
		<Name>div</Name>
		<OperandTypes>Operand.TYPE_REGISTER, Operand.TYPE_REGISTER, Operand.TYPE_REGISTER</OperandTypes>
		<OperandTypes>Operand.TYPE_REGISTER, Operand.TYPE_REGISTER, Operand.TYPE_IMMEDIATE</OperandTypes>
		<OperandTypes>Operand.TYPE_REGISTER, Operand.TYPE_REGISTER</OperandTypes>
		<Javacode>
		int quotient;
		int remainder;
		int rscontents = regs.getReg(rs);
		int rtcontents = regs.getReg(rt);
		quotient = rscontents / rtcontents;
		remainder = rscontents % rtcontents;
		regs.setReg("LO", quotient);
		regs.setReg("HI", remainder);
		</Javacode>
		<Type>Extended</Type>
		<CoreMachineCode>000000aaaaabbbbb0000000000011010</CoreMachineCode>
		<MachineCodeRepresentations>
			<Representation>
				<OperandsCoding>11</OperandsCoding>
				<MachineCode>000000aaaaabbbbb0000000000011010</MachineCode>
			</Representation>
			<Representation>
				<OperandsCoding>111</OperandsCoding>
				<MachineCode>000000bbbbbccccc00000000000110100000000000000000aaaaa00000010010</MachineCode>
				<!-- 	div b c
						mflo a
				-->
			</Representation>
			<Representation>
				<OperandsCoding>110</OperandsCoding>
				<MachineCode>0011010000000001cccccccccccccccc000000bbbbb0000100000000000110100000000000000000aaaaa00000010010</MachineCode>
				<!-- 	addi a c changed to ori
						div b c
						mflo a
				-->
				<Operands>
					<Op>
						<Number>3</Number>
						<Type>0</Type>
						<Mask>1111111111111111</Mask>
						<EncodeBits>16</EncodeBits>
						<OutputBits>16</OutputBits>
						<OffSetMode>2</OffSetMode>
					</Op>
				</Operands>
			</Representation>
			<Representation>
				<OperandsCoding>11a</OperandsCoding>
